import { Inter, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({ variable:'--font-inter', subsets: ["latin"], weight:['400', '200', '500', '300']});
const ibmPlexMono = IBM_Plex_Mono({variable:'--font-ibm-mono',subsets: ["latin"], weight:'300'});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${ibmPlexMono.variable}`}>{children}</body>
    </html>
  );
}
